### ISSUE TITLE
usbFunctionSetup's caller should be able to read out of PROGMEM

### ISSUE THREAD

**Issue by sowbug** [obdev/v-usb#10]
[WinUSB](https://msdn.microsoft.com/en-us/library/windows/hardware/ff537430) and [WebUSB](https://reillyeon.github.io/webusb/) requests are likely to be static and thus stored in PROGMEM, but usbFunctionSetup() has no built-in facility for handling responses stored in flash. While it's reasonably straightforward to implement usbFunctionRead() to return data out of flash, it seems like the sort of thing that many developers will eventually write themselves, and everyone's will be approximately the same.

Feature request: make it possible for usbFunctionSetup() to return with usbMsgPtr set to a PROGMEM address, and a global flag somewhere can indicate that it's a flash address, and then usbdrv.c can handle the rest.

**Comment by starkjohann** [comment]
Added feature. See documentation for `usbMsgFlags`.

**Comment by sowbug** [comment]
Awesome, thanks! I'll give it a try in my project (https://github.com/sowbug/weblight).
