### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Yangff** [obdev/v-usb#12]
https://github.com/obdev/v-usb/blob/master/circuits/Readme.txt

Most examples have a 1M **pull-down** resistor at D+. This **pull-up** ensures that
in self-powered

AND, I only seen pull-up res in D- in schs provided in that folder...

**Comment by starkjohann** [comment]
The pull-up on D- is 1.5k and identifies the device as low-speed. The 1M pull-down is only needed if the device should work stand-alone (without connection to the USB host). Most examples are bus-powered and therefore won't work without host anyway.
