### ISSUE TITLE
USB-IDs for free: what about composite devices

### ISSUE THREAD

**Issue by benjaminaigner** [obdev/v-usb#19]
Dear obdev team,

first of all, thank you very much for sharing the PIDs/VID with the community!
(overflo gave me the hint :-)).

I've a question regarding a composite device:

Out device (FLipMouse -> available [here, v2](https://github.com/asterics/FLipMouse) and [here, v3 (not completed)](https://github.com/asterics/FLipMouse-esp32) ) uses a composite device with mouse,keyboard,joystick and CDC-ACM. 

What PID do you recommend for this kind of device?

**Comment by itavero** [comment]
I also have a device that is a composite device consisting of a CDC ACM and MSC class device.
It currently already uses the default drivers for this, supplied by the operating system.

**Comment by benjaminaigner** [comment]
@itavero 

Thank you for the info, but I applied for a PID at NXP :-).

**Comment by itavero** [comment]
@benjaminaigner Your question is still not answered and I'd still like to know the answer (hence my comment indicating my use case). Could you reopen the issue?
