### ISSUE TITLE
AVR Assembly Compatibility

### ISSUE THREAD

**Issue by RobertDaleSmith** [obdev/v-usb#28]
I have an existing project written in 100% AVR assembly that I would like to extend it to include a basic USB hid joypad device. Is it possible and if so are there examples for implementing V-USB in a non C application?

**Comment by con-f-use** [comment]
I would go the other way and call your assembly code from C. Gcc even supports inline assembly but can generate the assembly from C code as well. It will be some work, though, either way seeing there are no direct examples and this repo is mostly abandoned.

**Comment by RobertDaleSmith** [comment]
Cool, I will probably go the route of calling my assembly code from C.

This repo is mostly abandoned? Is there a more active alternative?

**Comment by con-f-use** [comment]
If you find a well-maintained fork that actively develops it further, tell me.
