### ISSUE TITLE
Is a USB Hub implementation with multiple HID devices possible with V-USB alone?

### ISSUE THREAD

**Issue by RobertDaleSmith** [obdev/v-usb#29]
I built a video game controller adapter that uses USB for firmware updates (micronucleus bootloader) and converts Super Nintendo controllers to 3DO.

I thought it would be really cool if the adapter also could act as a USB joypad when the main application is active. My hardware has two Super Nintendo Controller inputs, so I was curious about how I could implement multiple HID devices simultaneously.

Is this even possible and does a USB hub code example exist?

**Comment by con-f-use** [comment]
HID specification supports the device acting as multiple devices, i.e. a mouse, controller and keyboard, you just have to use the right HID-descriptor. v-usb however, cannot act as a hub, it's a client only.

**Comment by RobertDaleSmith** [comment]
Okay cool. So I should be able to use V-USB to make a single device appear as many. But simulating a USB hub is no the right approach I guess.
